# gastro/docker-compose.yml
version: '3.8'

services:
  database:
    image: postgres:13
    env_file: .env  # 👈 Lê da raiz
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: ./backend/.env  # 👈 Lê do backend
    ports:
      - "${BACKEND_PORT}:3001"
    depends_on:
      - database

  frontend:
    build: ./frontend
    env_file: ./frontend/.env.local  # 👈 Lê do frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend

volumes:
  postgres_data: