version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: gastro_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gastro_user
      POSTGRES_PASSWORD: gastro_pass
      POSTGRES_DB: gastro_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: gastro_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: gastro_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

volumes:
  pgdata:
